services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: LGDXRobotCloud
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./certs/rootCA.crt:/certs/rootCA.crt
      - ./certs/redis_server.crt:/certs/redis_server.crt
      - ./certs/redis_server.key:/certs/redis_server.key

  api:
    image: yukaitung/lgdxrobotcloud.api
    ports:
      - 5162:5162
      - 5163:5163
    restart: always
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: ""
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/App/app.pfx"
    volumes:
      - ./appsettings.api.json:/App/appsettings.json
      - ./certs/grpc.pfx:/App/grpc.pfx
      - ./certs/app.pfx:/App/app.pfx
      - ./certs/rootCA.crt:/etc/ssl/certs/rootCA.crt
      - ./certs/rootCA.pfx:/root/.dotnet/corefx/cryptography/x509stores/my/rootCA.pfx
      - ./certs/redis_client.pfx:/root/.dotnet/corefx/cryptography/x509stores/my/redis_client.pfx
    depends_on:
      - postgres
      - rabbitmq
      - redis

  ui:
    image: yukaitung/lgdxrobotcloud.ui
    ports:
      - 5102:5102
      - 5103:5103
    restart: always
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: ""
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/App/app.pfx"
    volumes:
      - ./appsettings.ui.json:/App/appsettings.json
      - ./certs/ui.pfx:/root/.dotnet/corefx/cryptography/x509stores/my/ui.pfx
      - ./certs/redis_client.pfx:/root/.dotnet/corefx/cryptography/x509stores/my/redis_client.pfx
      - ./certs/app.pfx:/App/app.pfx
      - ./certs/rootCA.crt:/etc/ssl/certs/rootCA.crt
    depends_on:
      - api
      - rabbitmq
      - redis

  worker:
    image: yukaitung/lgdxrobotcloud.worker
    restart: always
    volumes:
      - ./appsettings.worker.json:/App/appsettings.json
    depends_on:
      - api
      - postgres
      - rabbitmq

  data:
    image: yukaitung/lgdxrobotcloud.data
    restart: "no"
    volumes:
      - ./appsettings.data.json:/App/appsettings.json
    depends_on:
      - postgres

volumes:
  pgdata: